spring:
  datasource:
    url: jdbc:mysql://10.10.20.64:3306/housedb?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: test
    password: test
server:
  port: 8080

logging:
  config: classpath:logback-dev-boot.xml
