server:
  servlet:
    context-path: /ucp-manage
    session:
      timeout: 1800
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
  web:
    resources:
      static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
  http:
    multipart:
      max-file-size: 2MB
      max-requset-size: 10MB
  profiles:
    active: dev

login:
  uri: /login
  need: false